FROM php:8.2-fpm

ARG NODE_VERSION=20
ARG COMPOSER_VERSION=2.7.2

RUN apt-get update && apt-get install -y \
    git \
    unzip \
    libpng-dev \
    libjpeg-dev \
    libzip-dev \
   
    && apt-get clean && rm -rf /var/lib/apt/lists/* # Bonne pratique Docker

RUN docker-php-ext-install pdo_mysql opcache bcmath zip gd

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer --version=$COMPOSER_VERSION

RUN curl -fsSL https://deb.nodesource.com/setup_$NODE_VERSION.x | bash - && \
    apt-get install -y nodejs

WORKDIR /var/www/html

COPY ./site1 /var/www/html/

COPY .env /var/www/html/.env

COPY ./site1/docker/php/entrypoint.sh /usr/local/bin/entrypoint.sh

RUN chmod +x /usr/local/bin/entrypoint.sh

EXPOSE 9000

ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]
